eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  #数据库
  datasource:
    #地址
    url: jdbc:mysql://localhost:3306/gar-2.1.x?useUnicode=true&characterEncoding=utf8&useSSL=false
    #用户名
    username: root
    #密码
    password: root
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#服务器
server:
  #端口号
  port: 8887
#日志
logging:
  file: C:/log/my_log.log
  level:
    pub: DEBUG