eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  #数据库
  datasource:
    #地址
    url: jdbc:mysql://localhost:3306/gar-2.x.x?useUnicode=true&characterEncoding=utf8&useSSL=false
    #用户名
    username: root
    #密码
    password: 19910405
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: true
    prefix: classpath:/templates/
    suffix: .html
#服务器
server:
  #端口号
  port: 8887
#日志
logging:
  file: C:/log/my_log.log
  level:
    pub: ERROR