shiro:
  # 是否启用shiro权限拦截
  enabled: false
  # 用于获取用户sessionId的cookie名
  session-id-name: token
  # session校验周期
  session-validation-interval: 1800000
  # session超时时间
  session-time-out: 1800000
  # cookie有效时间 默认-1
  cookie-max-age: -1
  # 缓存类型: ehcache、redis(未实现)
  cache-type: ehcache
  # 是否打开认证缓存
  enabled-authentication-caching: false
  # 是否打开授权缓存
  enabled-authorization-caching: true
  # 缓存配置文件路径
  ehcache-config-location: classpath:ehcache/shiro-ehcache.xml
  ehcache-authentication-name: shiro-authenticationCache
  ehcache-authorization-name: shiro-authorizationCache
  login-user-name-param: username
  login-pass-word-param: password
  # 是否开启form表单登录功能
  enabled-form-login: true
  # 是否开启ajax登录功能
  enabled-ajax-login: true
  # 用于鉴别是否是ajax请求的请求头key
  ajax-header-key: X-Requested-With
  # 用于鉴别是否是ajax请求的请求头value
  ajax-header-value: XMLHttpRequest
  # 登录请求地址
  login-post-url: /api-gar/post/login
  # 登录页面地址
  # 当未登录时访问页面,将根据访问根路径从zuul的数据库路由中进行匹配,匹配到对应微服务将重定向到对应微服务配置的登录地址
  # 如果没有匹配到对应微服务,将跳转到该地址
  login-page-url: /view/login
  # 登录成功跳转地址
  login-success-url: /view/home
  filter:
    loginUrl: /login
    unauthorizedUrl: /view/noAuthority
    formFilterName: authc
# 该配置文件用于配置本服务API的对应接口实现服务的相关信息
# 如 module 模块的API 实现于本服务内,所以name属性为当前服务名 ${spring.application.name}
feign:
  gar:
    # 网关权限路由接口服务名
    gar-api-service-name: ${spring.application.name}
    # 网关权限路由接口服务地址
    gar-api-service-path: /api-gar
    # 模块接口服务名
    module-api-service-name: ${spring.application.name}
    # 模块接口服务地址
    module-api-service-path: /api-gar-module
    # 角色接口服务名
    role-api-service-name: ${spring.application.name}
    # 角色接口服务地址
    role-api-service-path: /api-gar-role
    # 资源接口服务名
    resource-api-service-name: ${spring.application.name}
    # 资源接口服务地址
    resource-api-service-path: /api-gar-resource
    # 角色资源接口服务名
    role-resource-api-service-name: ${spring.application.name}
    # 角色资源接口服务地址
    role-resource-api-service-path: /api-gar-role-resource
    # 对象角色接口服务名
    object-role-api-service-name: ${spring.application.name}
    # 对象角色接口服务地址
    object-role-api-service-path: /api-gar-object-role
    # 对象接口服务名
    object-api-service-name: ${spring.application.name}
    # 对象接口服务地址
    object-api-service-path: /api-gar-object
    # 账户接口服务名
    account-number-api-service-name: ${spring.application.name}
    # 账户接口服务地址
    account-number-api-service-path: /api-gar-account
    # 子模块接口服务名
    sub-module-api-service-name: ${spring.application.name}
    # 子模块接口服务地址
    sub-module-api-service-path: /api-gar-sub-module
    # 模板接口服务名
    template-api-service-name: ${spring.application.name}
    # 模板接口服务地址
    template-api-service-path: /api-gar-template
    # 路由接口服务名
    route-api-service-name: ${spring.application.name}
    # 路由接口服务地址
    route-api-service-path: /api-gar-route
    # 路由视图接口服务名
    route-view-api-service-name: ${spring.application.name}
    # 路由视图接口服务地址
    route-view-api-service-path: /api-gar-route-view
    # 路由视图模板接口服务名
    route-view-template-api-service-name: ${spring.application.name}
    # 路由视图模板接口服务地址
    route-view-template-api-service-path: /api-gar-route-view-template
    # 角色路由视图模板接口服务名
    role-route-view-template-api-service-name: ${spring.application.name}
    # 角色路由视图模板接口服务地址
    role-route-view-template-api-service-path: /api-gar-role-route-view-template
    # 菜单组接口服务名
    menu-group-api-service-name: ${spring.application.name}
    # 菜单组接口服务地址
    menu-group-api-service-path: /api-gar-menu-group
    # 菜单接口服务名
    menu-api-service-name: ${spring.application.name}
    # 菜单接口服务地址
    menu-api-service-path: /api-gar-menu
    # 角色菜单接口服务名
    role-menu-api-service-name: ${spring.application.name}
    # 角色菜单接口服务地址
    role-menu-api-service-path: /api-gar-role-menu
    # 菜单路由接口服务名
    menu-route-api-service-name: ${spring.application.name}
    # 菜单路由接口服务地址
    menu-route-api-service-path: /api-gar-menu-route