spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    include: dev-multiple-data-source,dev-multiple-redis
#服务器
server:
  #端口号
  port: 8080
#日志
logging:
  level:
    root: info
  file:
    path: logs