spring:
  avalon:
    # 微信
    wechat:
      # 公众号
      official-account:
        # 是否启用, 默认 false
        enabled: true
        # 第三方用户唯一凭证
        app-id: wx61dfdf905b1f4a8a
        # 第三方用户唯一凭证密钥, 即 appsecret
        secret: 2a607cb5de6fe9aa89a2d8a761dc3c05
        # 用于获取 access_token 的url
        access-token-get-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${spring.avalon.wechat.official-account.app-id}&secret=${spring.avalon.wechat.official-account.secret}
        # 是否使用自动刷新 access_token 功能, 默认 true
        auto-refresh-access-token: true
        # 自动刷新 access_token 间隔, 单位毫秒, 默认 7200000 即2小时
        auto-refresh-access-token-interval: 7200000
        # 用于对接公众号的token
        token: WECHAT-OFFICIAL-ACCOUNT-TOKEN
        # 入口根路径
        entrance-root-path: /wechat/official/account
        # 入口子路径
        entrance-sub-path: /index
