spring:
  avalon:
    security:
      # 是否启用安全模块
      enabled: false
      # 缓存类型: EHCACHE、REDIS
      cache-type: REDIS
      http:
        # 用于鉴别是否是ajax请求的请求头key
        ajax-header-identification-key: X-Requested-With
        # 用于鉴别是否是ajax请求的请求头value
        ajax-header-identification-value: XMLHttpRequest
      session:
        # 用于获取用户sessionId的cookie名
        session-id-name: token
        # session校验周期
        session-validation-interval: 1800000
        # session超时时间, 注意,该配置受缓存框架影响
        session-time-out: 86400000
        # cookie有效时间 默认-1
        cookie-max-age: 86400000
        # 会话缓存名 如果使用ehcache 则配置文件相关name应保持一致
        session-cache-name: activeSessionCache
      authentication:
        # 是否打开认证缓存, 一般不打开
        cache-enabled: false
        # 认证缓存名 如果使用ehcache 则配置文件相关name应保持一致
        cache-name: authenticationCache
        # 登录用户名key,一般为username
        user-name-key: username
        # 登录用户密码key,一般为password
        pass-word-key: password
        # 登录请求地址 微服务架构需要带上微服务前缀地址如：/route-gar
        url: /gar/api-gar/post/login
        #  url: /route-gar/api-gar/post/login
        # 登录页面地址
        # 当未登录时访问页面,将根据访问根路径从zuul的数据库路由中进行匹配,匹配到对应微服务将重定向到对应微服务配置的登录地址
        # 如果没有匹配到对应微服务,将跳转到该地址
        page-url: /view/login
        # 登录成功跳转地址
        success-url: /view/home
        # redis 配置, 仅当cache-type为redis时有效
      authorization:
        # 是否打开授权缓存, 一般打开
        cache-enabled: true
        # 授权缓存名 如果使用ehcache 则配置文件相关name应保持一致
        cache-name: authorizationCache
        # redis 配置, 仅当cache-type为redis时有效
      # ehcache 配置, 仅当cache-type为ehcache时有效
      ehcache:
        # ehcache配置文件路径
        cache-manager-config-file: classpath:ehcache/shiro-ehcache.xml
      filter:
        login-url: /login
        unauthorized-url: /view/noAuthority
        form-filter-name: authc
        # 放行的资源
        release-resources:
        # 放行静态资源
        - ${spring.mvc.static-path-pattern}
        # 放行公众号相关接口
        - /wechat/official/account/**
        - /wechat/official/account/web/page/authorization/**