spring:
  avalon:
    # 微信
    wechat:
      # 公众号
      official-account:
        # 是否启用, 默认 false
        enabled: false
        # 第三方用户唯一凭证
        app-id: wx61dfdf905b1f4a8a
        # 第三方用户唯一凭证密钥, 即 appsecret
        secret: 2a607cb5de6fe9aa89a2d8a761dc3c05
        # 用于获取 access_token 的url
        access-token-get-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${spring.avalon.wechat.official-account.app-id}&secret=${spring.avalon.wechat.official-account.secret}
        # 是否使用自动刷新 access_token 功能, 默认 true
        auto-refresh-access-token: true
        # 自动刷新 access_token 间隔, 单位毫秒, 默认 7200000 即2小时
        auto-refresh-access-token-interval: 7200000
        # 用于对接公众号的token
        token: WECHAT-OFFICIAL-ACCOUNT-TOKEN
        # 公众号入口根路径
        api-entrance-root-path: /wechat/official/account
        # 公众号入口子路径
        api-entrance-sub-path: /index
        # 网页授权
        web-page-authorization:
          # 开放授权地址, 如果配置了其它属性如 redirect-uri、scope、response-type、state 会在系统内部追加到本地址上
          oauth2-path: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${spring.avalon.wechat.official-account.app-id}
          # 授权后重定向的回调链接地址
          redirect-uri:
          # 应用授权作用域
          scope: snsapi_base
          # 返回类型
          response-type: code
          # 重定向后会带上state参数，开发者可以填写a-zA-Z0-9的参数值，最多128字节
          state:
          # 用于获取网页 access_token 的url
          access-token-get-url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${spring.avalon.wechat.official-account.app-id}&secret=${spring.avalon.wechat.official-account.secret}&grant_type=authorization_code
          # 用于刷新网页 access_token 的url
          access-token-refresh-url: https://api.weixin.qq.com/sns/oauth2/refresh_token?appid=${spring.avalon.wechat.official-account.app-id}&grant_type=refresh_token
          # 用于获取网页用户信息的url
          user-info-get-url: https://api.weixin.qq.com/sns/userinfo?lang=zh_CN
          # 用于校验网页 access_token 的url
          access-token-validation-url: https://api.weixin.qq.com/sns/auth
          # 网页授权根路径
          api-root-path: /wechat/official/account/web/page/authorization
          # 获取网页授权地址
          # 支持携带参数, 格式: /get/oauth2Path/{param} | /get/oauth2Path?name=xx&age=xx
          api-get-oauth2-path: /get/oauth2Path
          # 重定向到网页授权地址, 页面需要通过 window.location.href 访问该地址, 如果后端为内网需要进行转发
          # 支持携带参数, 格式: /get/oauth2Path/{param} | /get/oauth2Path?name=xx&age=xx
          api-redirect-oauth2-path: /redirect/oauth2Path
          # 接收微信code地址, 如果 ? 参数传递过 redirect_uri 则会重定向到该地址
          api-accept-code-path: /accept/code
          # 获取网页授权 access_token
          # 传递参数 key 可以获取到缓存数据, key => 微信返回的state
          api-get-web-page-access-token-path: /get/webPageAccessToken
          # 获取网页授权用户信息
          # 传递参数 key 可以获取到缓存数据, key => 微信返回的state
          api-get-user-info-path: /get/userInfo
          # 网页授权state缓存 用于缓存传递数据
          api-oauth2-state-cache:
            # 缓存别名
            alias: WECHAT_OFFICIAL_ACCOUNT_OAUTH2_STATE
        # 自定义菜单
        custom-menu:
          # 菜单创建地址
          menu-create-url: https://api.weixin.qq.com/cgi-bin/menu/create