# 多redis配置
spring:
  session:
    store-type: redis
  redis:
    #timeout: 3000
    host: localhost
    port: 6379
    password: root
    #password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8