# 多数据源配置
#数据库
spring:
  datasource:
    ds0-master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/gar-2.1.x?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root