# 多数据源配置
#数据库
spring:
  datasource:
    ds0-master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.11:3306/dms3.0?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root